name: Django-app workflow

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        # Обновление pip
        python -m pip install --upgrade pip
        # Установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # Установка зависимостей
        pip install -r requirements.txt
    
    - name: Test with flake8 and django tests
      run: |
        # Проверка проекта по flake8
        python -m flake8
        # Перейти в папку с manage.py и запустить тесты
        cd infra_project
        python manage.py test
